### PR TITLE
Update facebook wrapper to use graph api version 2.8

### PR DESCRIPTION
**Pull request by gaganawhad**

### CODE REVIEW

**Comment by gaganawhad** [comment]
[Determine if we Need to do Anything for FB v2.2 Upgrade](https://trello.com/c/84oIEL37/2944-determine-if-we-need-to-do-anything-for-fb-v2-2-upgrade)

**Comment by gaganawhad** [comment]
@benhutton let me know if you have any insight into the error we hit on circle.

**Comment by benhutton** [comment]
@gaganawhad this comes from being super loose in the gemspec. We are now testing against rails 5.1, right? Rails 5 deprecated passing in middleware names as strings, so 5.1 must have removed that. If you change to a constant instead of a string, it should work

**Comment by gaganawhad** [comment]
@benhutton this one is ready for your review again.

**Pull request merged**
