### PR TITLE
Switch url protocol default to https

### PR DESCRIPTION
**Pull request by benhutton**
@gaganawhad I _think_ this is all we need to convert wakes to start working with https urls for facebook metrics. Everything else _should_ be taken care of in the app. Please think this through with me and verify!

@chrismaddocks I'm not 100% sure I follow everything the solidjoys code is doing. Can you make sure that this change doesn't break anything there?

### CODE REVIEW

**Comment by benhutton** [comment]
[Make wakes protocol aware](https://trello.com/c/diKuiPUR/68-make-wakes-protocol-aware)

**Comment by benhutton** [comment]
@chrismaddocks I'm also a bit unsure about `URIFromLocationString`, in https://github.com/desiringgod/wakes/pull/22/commits/951ba28c3bc8180c218e6ad6d619a3c0d6f1a743

**Comment by chrismaddocks** [comment]
@benhutton @gaganawhad The Solid Joys code is working. This just allows us to store `solidjoys.desiringGod.org` locations in Wakes, so we can aggregate metrics from the legacy site with metrics from their newer locations on our main host.

Regarding `URIFromLocationString`: the scheme shouldn't matter here. This is essentially a helper class to get host and path information from a location string that may or may not be a URL. We're just adding `http` here so that we can use URI methods on it, but then the scheme and URI are discarded.

**Comment by chrismaddocks** [comment]
Do we need to deploy https://github.com/desiringgod/www/pull/3346 before merging this? (Or at least before updating the gem?) I assume this will also immediately change the URLs we're querying for metrics.

**Comment by benhutton** [comment]
@chrismaddocks @gaganawhad this should get shipped in the same PR that turns `force_ssl` on.

**Comment by gaganawhad** [comment]
@benhutton yeah, we can get this merged in and then I can add in the wakes updates to that PR.

**Pull request merged**
