### PR TITLE
Add Twitter count fields to Wakes

### PR DESCRIPTION
**Pull request by chrismaddocks**
https://trello.com/c/v8AYs0gz/2013-add-twitter-share-count-data-to-wakes

### CODE REVIEW

**Comment by chrismaddocks** [comment]
Hey @gaganawhad, I just assigned this to you. I know you've got a lot on your plate, but this is the other half the Twitter count PR you are already reviewing (and it's very straightforward).

**Comment by gaganawhad** [comment]
Sounds good @chrismaddocks!

**Comment by gaganawhad** [comment]
@chrismaddocks I got to sneak in some of my facebook metrics code without a test ... alas I had to write it [here](https://github.com/desiringgod/wakes/pull/16),  so that I can ask you to write a corresponding test for twitter! :) Code looks great! :) Good to merge after we add the test in here https://github.com/desiringgod/wakes/pull/24

**Comment by gaganawhad** [comment]
@chrismaddocks test looks good. Mind squashing it into the previous commit? You can keep the commit message on the previous one.

**Comment by chrismaddocks** [comment]
@gaganawhad Squash is done!

**Comment by gaganawhad** [comment]
@chrismaddocks Merge on this branch is disabled. You'll have to rebase against `origin develop` and resolve conflicts if you hit any, to free up the merge.

**Comment by chrismaddocks** [comment]
@gaganawhad back to you. Guess our tests were too similar. :)

**Comment by gaganawhad** [comment]
:)

**Pull request merged**
