### PR TITLE
Get caught up on rubocop updates

### PR DESCRIPTION
**Pull request by gaganawhad**

### CODE REVIEW

**Comment by gaganawhad** [comment]
@benhutton how about this, to get the build to pass?

**Comment by benhutton** [comment]
@gaganawhad how hard is it to actually fix the failures?

**Comment by gaganawhad** [comment]
@benhutton I can actually autocorrect most of them, but the question that might come up is do we actually want to apply all the style changes.

**Comment by benhutton** [comment]
@gaganawhad which ones? We are likely doing them all in our primary app

**Comment by gaganawhad** [comment]
@benhutton oh really? let me submit an autocorrect

**Comment by gaganawhad** [comment]
ok, take a look here @benhutton ... this includes the autofixes. To do more work here, we should probably create a card for it and get to it a bit later.

**Comment by gaganawhad** [comment]
[Update Facebook Share Count Service to Handle API Failures Better](https://trello.com/c/bLY1f6hR/2925-update-facebook-share-count-service-to-handle-api-failures-better)

**Pull request merged**
